[env:lilygo_t_echo]
platform = nordicnrf52@10.9.0
board = nrf52840_dk_adafruit
framework = arduino
upload_protocol = nrfutil
monitor_speed = 115200

build_flags =
    -DCFG_DEBUG=0

lib_deps =
    bxparks/AceButton @ ^1.10.1

; GxEPD from official T-Echo repo
lib_extra_dirs =
    /home/tanvan/Temp/T-Echo/lib
